version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
      - redis
    networks:
      - default
    ports:
      - "8080:8080"
  
volumes:
  data: null
